### ISSUE TITLE
[BUG]使用MuityMC加载游戏报错

### ISSUE THREAD

**Issue by npcdna** [ET-Team/EnigTech2#272]
**描述BUG**
将EnigTech2-1.2.11拖入MultiyMc后，点击运行加载到一半卡主不动
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？
正常运行
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：
![捕获](https://user-images.githubusercontent.com/24528072/72204726-11782480-34b6-11ea-86d0-1a8b5f24b569.PNG)

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[21:05:39] [Client thread/INFO] [Config]: [OptiFine] *** Reloading textures ***
[21:05:39] [Client thread/INFO] [Config]: [OptiFine] Resource packs: Minecraft-Mod-Language-Modpack.zip
[21:05:58] [Client thread/INFO] [smoothfont]: Detected charWidthFloat[] of OptiFine.
[21:08:25] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[21:08:26] [Thread-15/INFO] [minecraft/SoundManager]: Initializing LWJGL OpenAL
[21:08:26] [Thread-15/INFO] [minecraft/SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:08:26] [Thread-15/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalStateException: Only one OpenAL context may be instantiated at any one time.
[21:08:26] [Thread-15/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.lwjgl.openal.AL.create(AL.java:113)
[21:08:26] [Thread-15/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.lwjgl.openal.AL.create(AL.java:102)
[21:08:26] [Thread-15/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.lwjgl.openal.AL.create(AL.java:206)
[21:08:26] [Thread-15/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
[21:08:26] [Thread-15/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
[21:08:26] [Thread-15/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
[21:08:26] [Thread-15/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.CommandThread.run(CommandThread.java:121)
[21:08:41] [Client thread/WARN] [smoothfont]: renderChar method might be replaced. Fix the space width to 4 (MC default).
MultiMC: 日志上传触发: 11 Jan 2020 21:10:06 +0800
MultiMC: 日志上传失败！
[21:10:12] [Sound Library Loader/WARN] [minecraft/SoundManager]: ERROR MESSAGE:
[21:10:12] [Sound Library Loader/INFO] [minecraft/SoundManager]: SoundSystem did not load after 30 seconds.
[21:10:12] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[21:10:16] [Thread-17/INFO] [minecraft/SoundManager]: Switching to No Sound
[21:10:16] [Thread-17/INFO] [minecraft/SoundManager]: (Silent Mode)
[21:10:16] [Sound Library Loader/INFO] [minecraft/SoundManager]: Sound engine started
Exception in thread "Thread-15"

**Comment by dong031001** [comment]
请附上文件而不是截取片段粘贴在这里

**Comment by dong031001** [comment]
而且，1G内存是绝对跑不动ET2的，想太多了。
