### ISSUE TITLE
[BUG]饕餮之果导致客户端退出服务端

### ISSUE THREAD

**Issue by dong031001** [ET-Team/EnigTech2#487]
**描述BUG**

**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

```
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V
	at crafttweaker.mc1120.player.MCFoodStats.setSaturationLevel(MCFoodStats.java:63) ~[MCFoodStats.class:?]
	at ZenClassContenttweakercontenttweaker\item\AdvancedFruit0.onItemUpdate(Unknown Source) ~[?:?]
	at com.teamacronymcoders.contenttweaker.modules.vanilla.items.ItemContent.onUpdate(ItemContent.java:254) ~[ItemContent.class:?]
	at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:526) ~[aip.class:?]
	at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:363) ~[aec.class:?]
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
[18:31:48] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: huxin lost connection: Internal server error
```

**Comment by friendlyhj** [comment]
emmm，也许可以 assign 一下我？
由于是个纯单机党，对于服务端问题一概不知。该 issue 是否是用服务器核心？是否是 forge 官端？
如果`::setFoodStats`方法实在不可用，也许我试试曲线救国，每隔10s给1s饱和buff？

**Comment by dong031001** [comment]
> emmm，也许可以 assign 一下我？
> 由于是个纯单机党，对于服务端问题一概不知。该 issue 用的是什么服务器核心？是否是 forge 官端？
> 如果`::setFoodLevel`方法实在不可用，也许我试试曲线救国，每隔10s给1s饱和buff？

据悉直接用的提供服务端开服。
